close();
clear();
x = input("Enter the first input sequence : ");
y = input("Enter the second input sequence : ");
[z, lag] = xcorr(x, y);
disp(z);
subplot(3,1,1);
stem(x);
xlabel('n');
ylabel('x[n]');
title('First Input Sequence');
subplot(3,1,2);
stem(y);
xlabel('n');
ylabel('y[n]');
title('Second Input Sequence');
subplot(3,1,3);
stem(lag,z);
xlabel('n');
ylabel('x[n]');
title("Cross-Correlated Sequence");